MyPortfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('ImgCap/', include('ProjImgCap.urls')),
    path('PdfQA/', include('PDF_QNA.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

PDF_QNA/urls.py
from django.urls import path
from . import views

app_name = 'PDF_QNA'

urlpatterns = [
    path('', views.pdf, name='pdf'),
    path('upload', views.upload_pdf, name="upload_pdf"), 
    path('qna', views.qna, name="qna") 
    # other paths...
]

ProjImgCap/urls.py
from django.urls import path
from . import views

app_name = 'ProjImgCap'

urlpatterns = [
    path('', views.Image_caption, name='ImageCaptioning'),
    path('upload', views.Generate_caption, name="GenerateCaption") ,
    path('delete_image/', views.delete_image , name = 'deleteimage')
    # other paths...
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.index, name='index'),
    # other paths...
]

ProjImgCap/models.py
from django.db import models

# Create your models here.
class imageUpload(models.Model):
    id = models.CharField(primary_key= True ,max_length=100)
    image = models.ImageField(upload_to='images')

ProjImgCap/views.py
from django.shortcuts import render,redirect
from django.core.cache import cache

from .utils.general import resume_checkpoint
from .utils.tokenizer import Tokenizer
from .utils.process_image import letterbox
import torch
import numpy as np
import cv2

from pathlib import Path
import gdown

from .models import imageUpload
import uuid
import os
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json


def get_all():
    model = cache.get('model')  
    tokenizer = cache.get('tokenizer')
    device = cache.get('device')                                            #try to get cached object if it exists

    if not model:
        device = 'cuda' if torch.cuda.is_available() else 'cpu' 
        if Path("ProjImgCap/saved_model/best.pt").exists() == False :
            gdown.download(id='1sc1l1AWDHsKsV_N9OpQcnjGfgwSwdggA', output='ProjImgCap/saved_model/best.pt')
        tokenizer = Tokenizer("ProjImgCap/saved_model/vocab.json")                    
        model = resume_checkpoint("ProjImgCap/saved_model/best.pt", tokenizer= tokenizer, resume_weight_only= True, device= device)
        cache.set('model', model, None)  
        cache.set('tokenizer', tokenizer, None)                             #cache them all
        cache.set('device', device, None)

    return model, tokenizer, device

# Create your views here.
def Image_caption(request):
    return render(request, "upload.html")

def Generate_caption(request):
    model, tokenizer, device = get_all()
    model.eval()
    if request.method == 'POST' and request.FILES.get('image', False):
        try:
            # Get the uploaded image
            img_unique_id = uuid.uuid4()
            image = request.FILES['image']
            
            # Save the image to a model instance
            my_model_instance = imageUpload(id=img_unique_id, image=image)
            my_model_instance.save()
            # Read the image contents into memory
            image.seek(0)  # Ensure you're reading from the start of the file
            file_bytes = np.frombuffer(image.read(), np.uint8)
            img = cv2.imdecode(file_bytes, cv2.IMREAD_COLOR)
            img = letterbox(img, (480, 480))
            img_in = torch.from_numpy(img).to(device).unsqueeze(0).permute(0, 3, 1, 2).contiguous().float() / 255
            pred = model.generate(img_in, tokenizer, device=device, greedy=True, top_k=5)
            caption = tokenizer.decode(pred)
            # Retrieve the image from db
            image_instance = imageUpload.objects.filter(id=img_unique_id).first()
            # Get the image URL
            image_url = image_instance.image.url
            context = {
                "caption": caption[0],
                "image_url": image_url,
                "image_id": str(img_unique_id)
            }
            return render(request, "output.html", context)
        except Exception as e:
            context = {
                "error": str(e),
                "image": None,
            }
            return render(request, "output.html", context)

    return render(request, "upload.html")

@csrf_exempt
def delete_image(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            image_id = data.get('image_id')
            image_instance = imageUpload.objects.filter(id=image_id).first()
            if image_instance:
                # Delete the image file from db
                image_path = image_instance.image.path
                if os.path.exists(image_path):
                    os.remove(image_path)
                
                # Delete the image instance from the database
                image_instance.delete()
                return JsonResponse({"message": "Image  sucesfully deleted"})
            else:
                return JsonResponse({"message": "Image found"}, status=404)
        except Exception as e:
            return JsonResponse({"message": str(e)}, status=500)
    return JsonResponse({"message": "Invalid request"}, status=400)

ProjImgCap/templates/output.html
{% extends "upload.html" %}

{% block canvas %}
{% if image_url %}
<img id='temp' src="{{ image_url }}">
<input type='text' value={{image_id}}>
{% endif %}
{% if error %}
        <p>Error: {{ error }}</p>
    {% endif %}
{% endblock canvas %}

{% block caption %}
<div id="bottom">
    <h2>Generated Caption :</h2>
    <div id="txt_box">
        {% if caption %}
        {{caption}}
        {% endif %}
    </div>
</div>
{% endblock caption %}

{% block script %}
<script>
    document.addEventListener("DOMContentLoaded", function() {
        // Delay execution by 3 seconds
        setTimeout(function() {
            const imageId = "{{ image_id }}";
            const csrfToken = "{{ csrf_token }}";
            if (imageId) {
                fetch("http://127.0.0.1:8000/ImgCap/delete_image/", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json",
                        "X-CSRFToken": csrfToken
                    },
                    body: JSON.stringify({ image_id: imageId })
                })
                .then(response => {
                    if (!response.ok) {
                        throw new Error("Network response was not ok " + response.statusText);
                    }
                    return response.json();
                })
                .then(data => console.log(data.message))
                .catch(error => console.error("Error deleting image:", error));
            }
        }, 3000);  // 3000 milliseconds = 3 seconds
    });
</script>
{% endblock script %}

ProjImgCap/templates/upload.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/styles1.css' %}">
        <script src="{% static 'javascript/SimpleImage.js' %}"></script>
        <script src="{% static 'javascript/scp.js' %}"></script>  
    </head>
    <body>
        <div id="tops">
            <form  id = 'back_button_form' action="{% url 'portfolio:index' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <button id = 'back_button_icon' type="submit">Back</button>
            </form>
            <a href="https://github.com/Kunal-Shaw-097/Image-captioning" target="_blank"><img id='github_icon' src="{% static 'github.png' %}  " alt=""></a>
        </div>
        <h1>Image Caption Generator</h1>
        <div id="top">
            <div id="canvas">
               {% block canvas %}
               
               {% endblock canvas %}
               <canvas id="canv1"></canvas>
            </div>
            <form method="POST" enctype="multipart/form-data" action="{% url 'ProjImgCap:GenerateCaption' %}">
                {% csrf_token %}
                ImageName:
                <input type="file" name="image" multiple="false" accept="image/*" id=finput onchange=display()>
                <input type="submit" value="Generate">
            </form>
        </div>
       {% block caption %} 
       
       {% endblock caption %}
    </body>
    {% block script %}{% endblock script %}
</html>